### ISSUE TITLE
Add tests to ensure the templates can compile

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-iso#1]
Add tests to ensure the templates can compile.

**Comment by CAMOBAP** [comment]
According to my understanding this should be tested with two command:
 - `metanorma --type iso iso-rice/document.adoc`
 - `metanorma --type iso international-standard/document.adoc`

Both commands above lead to 

```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1393:in `initialize': File name too long @ rb_sysopen - international-standard/data:image/png;base64,... 
         from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1393:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1393:in `copy_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:487:in `copy_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:404:in `block in cp'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1572:in `block in fu_each_src_dest'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1588:in `fu_each_src_dest0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1570:in `fu_each_src_dest'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:403:in `cp'
	from /Library/Ruby/Gems/2.3.0/gems/html2doc-0.8.6/lib/html2doc/mime.rb:91:in `block in image_cleanup'
	from /Library/Ruby/Gems/2.3.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:204:in `block in each'
	from /Library/Ruby/Gems/2.3.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `upto'
	from /Library/Ruby/Gems/2.3.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/html2doc-0.8.6/lib/html2doc/mime.rb:86:in `image_cleanup'
	from /Library/Ruby/Gems/2.3.0/gems/html2doc-0.8.6/lib/html2doc/base.rb:47:in `cleanup'
	from /Library/Ruby/Gems/2.3.0/gems/html2doc-0.8.6/lib/html2doc/base.rb:36:in `process_html'
	from /Library/Ruby/Gems/2.3.0/gems/html2doc-0.8.6/lib/html2doc/base.rb:12:in `process'
	from /Library/Ruby/Gems/2.3.0/gems/isodoc-0.9.11/lib/isodoc/word_function/postprocess.rb:24:in `toWord'
	from /Library/Ruby/Gems/2.3.0/gems/isodoc-0.9.11/lib/isodoc/word_function/postprocess.rb:17:in `postprocess'
	from /Library/Ruby/Gems/2.3.0/gems/isodoc-0.9.11/lib/isodoc/convert.rb:151:in `convert'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-iso-1.1.5/lib/metanorma/iso/processor.rb:36:in `output'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-0.3.11/lib/metanorma/compile.rb:194:in `block in process_extensions'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-0.3.11/lib/metanorma/compile.rb:185:in `each'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-0.3.11/lib/metanorma/compile.rb:185:in `process_extensions'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-0.3.11/lib/metanorma/compile.rb:20:in `compile'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/gems/metanorma-cli-1.1.6/exe/metanorma:137:in `<top (required)>'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/bin/metanorma:22:in `load'
	from /usr/local/Cellar/metanorma/1.1.6/libexec/bin/metanorma:22:in `<main>'
```

This issue already fixed in https://github.com/metanorma/html2doc/commit/83e9624f46886614ef41cd9b14ecc0f181d68ddc so we need wait for release

@ronaldtse  I have 2 questions:
 - are two command above enough to test docs?
 - `metanorma new` command doesn't work, should it?

**Comment by CAMOBAP** [comment]
@ronaldtse sorry I cannot move forward without reply for prev comment

@opoudjis maybe you can answer too?

**Comment by ronaldtse** [comment]
@CAMOBAP795 yes you are right.

> are two command above enough to test docs?

Yes.

> metanorma new command doesn't work, should it?

It should work, it was merged in https://github.com/metanorma/metanorma-cli/pull/35

**Comment by CAMOBAP** [comment]
@ronaldtse thanks for the reply, as far as I see it's not released yet so should we wait for a release or using Github's one, is ok?

**Comment by CAMOBAP** [comment]
@opoudjis maybe we have a planned release for metanorma-cli in near future?

**Comment by opoudjis** [comment]
I've lost track; @abunashir, have you finished your refactoring work?

**Comment by opoudjis** [comment]
I thought that updating metanorma-csand and metanorma-m3d would take care of the dependency. OK, I'll do a release of metanorma-cli later tonight or tomorrow.

**Comment by CAMOBAP** [comment]
> I thought that updating metanorma-csand and metanorma-m3d would take care of the dependency. 

Yep but this need for https://github.com/metanorma/metanorma-build-scripts/issues/1 & https://github.com/metanorma/chocolatey-metanorma/issues/23 tasks

BTW `metanorma-csand` is ok, but `metanorma-m3d` looks it was not pushed to ruby-gems yet

@opoudjis could you please doublecheck?

> I'll do a release of metanorma-cli later tonight or tomorrow.

👍 we need `metanorma-cli` release to be able to use `metanorma new ...` command

**Comment by opoudjis** [comment]
metanorma-m3d pushed.

**Comment by opoudjis** [comment]
I've just pulled metanorma-cli, and Travis breaks quite nastily all over master branch. So I will not be releasing it. @CAMOBAP795 and @abunashir, please talk to each other, and let me know when this gem is ready to release. @CAMOBAP795, note that @abunashir is finding a lot of Appveyor breakage in his current pull request.

**Comment by CAMOBAP** [comment]
> I've just pulled metanorma-cli, and Travis breaks quite nastily all over master branch. So I will not be releasing it

Hmm, master looks green https://travis-ci.org/metanorma/metanorma-cli , also I just executed `bundle exec rake` tests passed

@opoudjis could you please clarify what isn't right?

**Comment by opoudjis** [comment]
I've re-pulled now, and was able to get rspec to compile nicely, so I will have to assume that the issue has gone away. I have pushed metanorma-cli as a new gem.

**Comment by abunashir** [comment]
Hey Guys, I'm sorry, I overlooked this one. I have been thinking about it, so what exactly do we want to test here?

The CLI is copying the skeleton files to the metanorma templates directory without doing any sort of changes, and that is being tested in the metanorma cli gem, so why do we still need to have a dependency to the cli here from this repo?

All I can think of is to check that the standard files are present in this repo or not, and probably the easiest way might be to have specs that only check for the existence of files, and maybe verify some content, anything else?

cc: @ronaldtse, @CAMOBAP795

**Comment by ronaldtse** [comment]
@abunashir we need to make sure that we can test if the templates are compilable.

Here, for example, we want to ensure the `international-standard` etc templates can actually compile (i.e. does not contain errors that cause Metanorma to fail).

A possible approach is:

Make the `-g` option more flexible that it allows local Template Repositories (a directory, not only a Git repo). Then we can make the spec run `metanorma new -t iso -d international-standard -g ./` to test the template.

i.e. we want to use the "released" metanorma-cli gem to test this Template Repository.

**Comment by abunashir** [comment]
@ronaldtse What do you mean by compilable?

The `metanorma new` is basically copying the selected files from this repo to the new document with specified structure, but it doesn't change/verify anything not even if that's a valid ascii doc document or not, so how can we be sure that it's compilable?

So my point is we can definitely use the new command to generate the document here, but when it doesn't even check anything then what's exactly would it check and how meaningful would that be? Just that it can copy files in the right structure? Shouldn't that be tested in the CLI itself?

Form this repo prospective, what I would consider meaningful to test are the followings: Let's say this template support  `standard` template then the test could include

* This repo has the right structure with all important file in it.
* It has the existence of correct files `standard/*-document.adoc`, `standard/sections/*` and etc
* The file under the standard subdirectory are valid asciidoc, and properly included links
* If we want to be 100% sure then probably use soemthing similar to `metanorma compile` to see that it can actually compile without any error.


Let me know if I am missing something here.

**Comment by ronaldtse** [comment]
> * This repo has the right structure with all important file in it.

i.e. This Template Repository should meet its "requirements". That is:

* contains `{template-name}/` directories
* each template is valid
* (etc. ?)

> * It has the existence of correct files standard/*-document.adoc, standard/sections/* and etc

Each Template should be valid:
* contains a `document.adoc`
* the `sections/*` files are actually optional.
* (etc. ?)

> * The file under the standard subdirectory are valid asciidoc, and properly included links

Well, yes, but whether they are Asciidoc files a simple compilation will already show it.

Not sure if we need to ensure files are linked?

> * If we want to be 100% sure then probably use soemthing similar to metanorma compile to see that it can actually compile without any error.

This is what I meant -- I want to ensure that `metanorma compile` runs on a Template. This is 100% necessary -- the user who runs `metanorma new` must be able to immediately compile the document.

Further yet, the common files such as the `Makefile` should also run on the template, etc, but it might not be necessary..

**Comment by abunashir** [comment]
@ronaldtse sounds good to me, thanks!

**Comment by CAMOBAP** [comment]
Done
