### ISSUE TITLE
Document default in the ISO template: "If no obligation value is set, the annex is presumed to be normative."

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-iso#13]
For @manuel489

From @opoudjis:
> Won't fix, but you should document this default in the ISO template: "If no obligation value is set, the annex is presumed to be normative."

_Originally posted by @opoudjis in https://github.com/metanorma/mn-templates-iso/issues/9#issuecomment-549187495_

**Comment by manuelfuenmayor** [comment]
Done
