### ISSUE TITLE
Add in templates for all supported document types

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-iso#2]
https://github.com/metanorma/metanorma-iso/blob/01022e4f57dcd24db9e91cb95351b186fed60838/lib/asciidoctor/iso/isostandard.rng#L779

These document types are supported:

```
international-standard
technical-specification
technical-report
publicly-available-specification
international-workshop-agreement
guide
```

**Comment by opoudjis** [comment]
What... is this task? Are you asking me to create all these templates?

**Comment by ronaldtse** [comment]
Yes (it's not super urgent). We already have some in `metanorma-iso` specs, we could reuse those too.

**Comment by opoudjis** [comment]
Similar task to https://github.com/metanorma/metanorma/issues/53

**Comment by manuelfuenmayor** [comment]
`international-standard` template is existent.

**Comment by manuelfuenmayor** [comment]
Last two templates, `international-workshop-agreement` and `guide`, are added in https://github.com/metanorma/mn-templates-iso/pull/26

**Comment by ronaldtse** [comment]
@manuel489 we are still missing `technical-specification`. Can you please add it? Thanks.

**Comment by manuelfuenmayor** [comment]
Ok, all supported templates are now added. Closing.
